# Generated by Django 4.1.5 on 2023-01-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_alter_document_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Images',
        ),
    ]
