# Generated by Django 4.1.5 on 2023-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0003_rename_document_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
